version: '3.9'
services:
#  car-api:
#    container_name: car-api
#    hostname: car-api
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/carapp_db
#    depends_on:
#      - postgres-db

  postgres-db:
    image: postgres:15-bullseye
    restart: unless-stopped
    container_name: postgres-db
    hostname: postgres-db
    volumes:
      - ./initsqls/:/docker-entrypoint-initdb.d/
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: carapp_super_user
      POSTGRES_PASSWORD: test_db_password
      POSTGRES_DB: carapp_db
    ports:
        - "5432:5432"