services:
  postgres:
    image: 'postgres:latest'
    environment:
        POSTGRES_USER: carapp_super_user
        POSTGRES_PASSWORD: test_db_password
        POSTGRES_DB: carapp_db
    ports:
      - '5432:5432'
