#debug: true
spring:
#  main:
#      web-application-type: reactive
  datasource:
#    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/carapp_db}
    username: ${SPRING_DATASOURCE_USERNAME:carapp_super_user}
    password: ${SPRING_DATASOURCE_PASSWORD:test_db_password}
  #    hikari:
  #      maximum-pool-size: 1 #maximum pool size
  #      connection-timeout: 10000 #maximum number of milliseconds that a client will wait for a connection
  #      max-lifetime: 30000 #maximum idle time for connection
  #      connection-test-query: select 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        default_schema: ${SPRING_JPA_SCHEMA:carapp_schema}

  graphql:
    path: "/graphql"
    schema:
      introspection:
        enabled: true
      printer:
          enabled: true
      file-extensions:
        - ".graphqls"
        - ".gqls"
#        - ".graphql"
    graphiql:
      enabled: true
      path: "/graphiql"
#    websocket:
#        path: "/graphql"
  security:
    user:
      password: qweasd


jwt:
  secret: ${JWT_SECRET:"655368566D597133743677397A244326452948404D635166546A576E5A723475"}
  issuer: "carapp"
  expirationMinutes: 1440 # 1 DAY
  refreshExpirationMonth: 3

server:
  #  servlet:
  #    context-path: /tech
  port: ${PORT:8080}
  shutdown: GRACEFUL

logging:
    level:
        web: DEBUG

aws-s3:
  region: ${AWS_REGION:us-east-1}
  mediaFilesBucket: ""
  cloudfrontDistribution: ""


open-ai:
    key: ${OPENAI_KEY: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}
    url: https://api.openai.com

car-app:
    origins: https://api.liquidibrium.me, http://localhost:8080, https://car-app-api.up.railway.app/
