-- create schema if not exists carapp_schema;
--
-- create table user_otp
-- (
--     id                    uuid         not null
--         primary key,
--     created_at            timestamp(6),
--     expires_at            timestamp(6),
--     otp_hash              varchar(255),
--     otp_status            varchar(255) not null,
--     send_attempts         integer,
--     updated_at            timestamp(6),
--     verification_attempts integer,
--     verified_at           timestamp(6)
-- );
--
-- alter table user_otp
--     owner to carapp_super_user;
--
-- create table users
-- (
--     id          uuid         not null
--         primary key,
--     created_at  timestamp(6) not null,
--     firstname   varchar(255),
--     lastname    varchar(255),
--     phone       varchar(255) not null,
--     updated_at  timestamp(6),
--     user_role   varchar(255) not null,
--     user_otp_id uuid
--         constraint fk346bmu07eyf5cic5qevhmkanv
--             references user_otp
-- );
--
-- alter table users
--     owner to carapp_super_user;
--
-- create table car
-- (
--     id               uuid         not null
--         primary key,
--     car_type         varchar(255),
--     created_at       timestamp(6) not null,
--     make             varchar(255),
--     model            varchar(255),
--     plate_number     varchar(255),
--     tech_pass_number varchar(255),
--     updated_at       timestamp(6),
--     vin              varchar(255),
--     year             integer      not null,
--     owner_id         uuid
--         constraint fk2ivv310r5mebooqhp1362nbio
--             references users
-- );
--
-- alter table car
--     owner to carapp_super_user;
--
-- create table category
-- (
--     id         uuid not null
--         primary key,
--     created_at timestamp(6),
--     name       varchar(255),
--     name_ka    varchar(255),
--     updated_at timestamp(6)
-- );
--
-- alter table category
--     owner to carapp_super_user;
--
-- create table provider
-- (
--     id      uuid not null
--         primary key,
--     email   varchar(255),
--     logo    varchar(255),
--     name    varchar(255),
--     phone   varchar(255),
--     website varchar(255)
-- );
--
-- alter table provider
--     owner to carapp_super_user;
--
-- create table product
-- (
--     id             uuid             not null
--         primary key,
--     capacity       integer          not null,
--     city           varchar(255),
--     description    varchar(255),
--     description_ka varchar(255),
--     district       varchar(255),
--     images         varchar(255),
--     lat            double precision not null,
--     lng            double precision not null,
--     main_image     varchar(255),
--     name           varchar(255),
--     name_ka        varchar(255),
--     street         varchar(255),
--     tags           varchar(255),
--     category_id    uuid             not null
--         constraint fk1mtsbur82frn64de7balymq9s
--             references category,
--     provider_id    uuid             not null
--         constraint fkfmt6vehie8ep9pq0nnvv9een7
--             references provider
-- );
--
-- alter table product
--     owner to carapp_super_user;
--
-- create table product_details
-- (
--     id                       uuid not null
--         primary key,
--     available_services       varchar(255),
--     average_duration_minutes integer,
--     currency                 varchar(255),
--     description              varchar(255),
--     description_ka           varchar(255),
--     name                     varchar(255),
--     name_ka                  varchar(255),
--     not_available_services   varchar(255),
--     prices_for_car_types     varchar(255),
--     product_id               uuid
--         constraint fkrhahp4f26x99lqf0kybcs79rb
--             references product
-- );
--
-- alter table product_details
--     owner to carapp_super_user;
--
-- create table schedule
-- (
--     id                 uuid not null
--         primary key,
--     car_id             uuid,
--     category_id        uuid,
--     product_id         uuid,
--     scheduling_date    date,
--     scheduling_time    time,
--     product_details_id uuid
--         constraint fk7u0405c08466sx3xhepjoc2o2
--             references product_details,
--     user_id            uuid
--         constraint fka50n59y1j4a6qwa42p8jiguds
--             references users
-- );
--
-- alter table schedule
--     owner to carapp_super_user;
--
