name: Build

on:

    workflow_dispatch:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Java 17
              uses: actions/setup-java@v3
              with:
                  distribution: 'corretto'
                  java-version: "17"
            - name: Build gradle
              run: |
                  chmod +x ./gradlew
                  ./gradlew bootJar
            -   name: Docker build
                run: |
                    docker build . -t carz-api
#                    docker run --rm -it -e STAGE='test' -d -p 8080:8080 carz-api
#
#            -   name: Health check
#                run: |
#                    chmod +x scripts/health-check.sh
#                    scripts/health-check.sh http://localhost:8080/actuator/health
