name: Deploy to Railway

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Java 17
              uses: actions/setup-java@v3
              with:
                distribution: 'corretto'
                java-version: "17"
            - name: Build gradle
              run: |
                  chmod +x ./gradlew
                  ./gradlew bootJar

            - name: Install Railway
              run:  curl -X POST ${{ secrets.RENDER_HOOK }}

